name: Newman - Postman Tests

on:
  workflow_dispatch:  # M칬jligg칬r manuell k칬rning av workflowet

jobs:
  postman-tests:
    runs-on: ubuntu-latest  # K칬r p친 en Ubuntu-milj칬

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # H칛mtar koden fr친n ditt repo

      # 游댳 Installera .NET
      - name: Install .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0'  # 츿ndra om du anv칛nder en annan version

      # 游댳 Bygg .NET-projektet
      - name: Build .NET project
        run: |
          cd server  # Navigera till mappen d칛r API:t finns
          dotnet restore  # 칀terst칛ll beroenden
          dotnet build --configuration Release  # Bygg projektet
          dotnet run &  # Starta servern i bakgrunden

      # 游댳 Installera Newman (Postman CLI)
      - name: Install Newman
        run: npm install -g newman  # Installerar Newman f칬r att k칬ra Postman-tester

      # 游댳 V칛nta lite s친 att servern startar
      - name: Wait for API to be ready
        run: sleep 10s  # V칛ntar 10 sekunder (justera vid behov)

      # 游댳 K칬r Postman Collection
      - name: Run Postman Collection
        uses: gasparhe/newman-action@1.0.0
        with:
          collection: server/APIcollection.json  # Din Postman-kollektion
          environment: server/APIenvironment.json  # Din milj칬fil (칛ndra om den heter n친got annat)
